"""Fast Expression generation and AST validation pipeline with automated syntax retry.

Orchestrates LLMs to generate quantitative alpha candidates, validates each candidate
locally using the Fast Expression AST parser and operator checker, and executes automated
repair/retry loops for expressions violating BRAIN's 8-operator or 3-field constraints.
"""

from __future__ import annotations

import json
import re
import time
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

import structlog

from ..labs.fastexpr import (
    GROUPING,
    MAX_FIELDS,
    MAX_OPERATORS,
    OperatorInfo,
    ParseError,
    data_fields,
    operator_count,
    operator_table,
    parse,
    render,
    validate,
)
from ..prompts.library import PromptLibrary, StrategyCategory


if TYPE_CHECKING:
    from ..discovery.catalog import CatalogDiscovery
    from ..llm.service import LLMService

log = structlog.get_logger(__name__)

# JSON schema enforced for Google Gemini models and requested from all providers
CANDIDATE_RESPONSE_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "batch_summary": {"type": "string"},
        "candidates": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "hypothesis": {"type": "string"},
                    "expression": {"type": "string"},
                    "category": {"type": "string"},
                    "target_dataset": {"type": "string"},
                    "primary_fields": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                },
                "required": ["hypothesis", "expression"],
            },
        },
    },
    "required": ["candidates"],
}


CORE_BRAIN_OPERATOR_DEFS = [
    "ts_rank(x, d)",
    "ts_zscore(x, d)",
    "ts_delta(x, d)",
    "ts_delay(x, d)",
    "ts_mean(x, d)",
    "ts_std_dev(x, d)",
    "ts_corr(x, y, d)",
    "ts_covariance(x, y, d)",
    "ts_sum(x, d)",
    "ts_product(x, d)",
    "ts_decay_linear(x, d)",
    "ts_argmax(x, d)",
    "ts_argmin(x, d)",
    "ts_backfill(x, d)",
    "rank(x)",
    "group_rank(x, group)",
    "group_neutralize(x, group)",
    "group_mean(x, group)",
    "group_zscore(x, group)",
    "abs(x)",
    "log(x)",
    "sign(x)",
    "sqrt(x)",
    "fraction(x)",
    "max(x, y)",
    "min(x, y)",
    "power(x, y)",
    "scale(x, target=1)",
    "trade_when(cond, alpha, exit)",
    "vec_avg(x)",
    "vec_sum(x)",
]

BUILTIN_OPERATOR_TABLE: dict[str, OperatorInfo] = operator_table(
    [
        {"name": d.split("(")[0], "definition": d, "category": "CORE"}
        for d in CORE_BRAIN_OPERATOR_DEFS
    ]
)


def sanitize_expression(raw_expr: str) -> str:
    """Pre-cleans and normalizes LLM-generated Fast Expressions.

    Strips markdown code fences, wrapping quotes, common variable assignment prefixes
    (e.g. 'alpha =', 'return '), Python logical keywords ('and', 'or', 'not'),
    and trailing semicolons.
    """
    if not raw_expr:
        return ""

    expr = raw_expr.strip()

    # 1. Strip markdown fences if present
    fence_match = re.search(r"```(?:\w+)?\s*([\s\S]*?)\s*```", expr)
    if fence_match:
        expr = fence_match.group(1).strip()

    # 2. Strip surrounding quotes (double, single, backticks)
    if (expr.startswith(('"', "'", "`")) and expr.endswith(('"', "'", "`"))) and len(expr) >= 2:
        expr = expr[1:-1].strip()

    # 3. Strip common assignment prefixes like "alpha =", "signal =", "result =", "return "
    expr = re.sub(
        r"^(?:alpha|signal|expression|result|factor|ret)\s*=\s*", "", expr, flags=re.IGNORECASE
    )
    expr = re.sub(r"^return\s+", "", expr, flags=re.IGNORECASE)

    # 4. Strip trailing semicolons
    expr = expr.rstrip(";").strip()

    # 5. Replace Python logical keywords with Fast Expression symbols
    expr = re.sub(r"\bnot\s+", "!", expr)
    expr = re.sub(r"\band\b", "&&", expr)
    expr = re.sub(r"\bor\b", "||", expr)

    # 6. Normalize multiline expressions into a single line
    expr = re.sub(r"\s+", " ", expr).strip()

    return expr


@dataclass(slots=True)
class CandidateValidationResult:
    """Outcome of offline AST validation against WorldQuant BRAIN grammar."""

    is_valid: bool
    expression: str
    error: str | None = None
    operator_count: int = 0
    field_count: int = 0
    fields_used: list[str] = field(default_factory=list)
    retry_count: int = 0
    repair_history: list[str] = field(default_factory=list)


@dataclass(slots=True)
class GeneratedCandidate:
    """One candidate alpha factor generated by an LLM researcher."""

    hypothesis: str
    expression: str
    category: str
    target_dataset: str | None
    primary_fields: list[str]
    validation: CandidateValidationResult
    raw_response: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class GenerationBatch:
    """A complete round of candidate alphas from one researcher."""

    summary: str
    candidates: list[GeneratedCandidate]
    model_ref: str
    total_tokens: int
    duration_seconds: float

    @property
    def valid_count(self) -> int:
        return sum(1 for c in self.candidates if c.validation.is_valid)

    @property
    def valid_rate(self) -> float:
        return (self.valid_count / len(self.candidates)) if self.candidates else 0.0


def validate_expression(
    expr: str,
    valid_names: set[str] | None = None,
    op_table: dict[str, Any] | None = None,
    check_operators: bool = False,
) -> CandidateValidationResult:
    """Validates an expression offline against BRAIN grammar and constraints.

    Checks:
    1. Pre-sanitizes code fences, quotes, assignment prefixes, and Python logical keywords
    2. Fast Expression syntax parseability
    3. Operator count <= 8 (ts_backfill uncounted)
    4. Distinct data fields <= 3 (grouping fields uncounted)
    5. Operator arities and existence (if op_table provided or check_operators=True)
    """
    clean_expr = sanitize_expression(expr)
    if not clean_expr:
        return CandidateValidationResult(
            is_valid=False,
            expression=clean_expr,
            error="Expression is empty",
        )

    try:
        tree = parse(clean_expr)
    except ParseError as exc:
        return CandidateValidationResult(
            is_valid=False,
            expression=clean_expr,
            error=f"Syntax parse error: {exc}",
        )

    # 1. Check operator count
    ops = operator_count(tree)
    if ops > MAX_OPERATORS:
        return CandidateValidationResult(
            is_valid=False,
            expression=clean_expr,
            error=f"Operator count ({ops}) exceeds WorldQuant BRAIN limit of {MAX_OPERATORS}",
            operator_count=ops,
        )

    # 2. Check data fields count
    used_fields = data_fields(tree)
    data_only = [f for f in used_fields if f not in GROUPING]
    if len(data_only) > MAX_FIELDS:
        return CandidateValidationResult(
            is_valid=False,
            expression=clean_expr,
            error=(
                f"Data field count ({len(data_only)}: {', '.join(data_only)}) "
                f"exceeds limit of {MAX_FIELDS}"
            ),
            operator_count=ops,
            field_count=len(data_only),
            fields_used=data_only,
        )

    # 3. Check operator arity and names if table available or check_operators requested
    table_to_use = op_table or (BUILTIN_OPERATOR_TABLE if check_operators else None)
    if table_to_use:
        names_to_check = (valid_names or set()) | set(used_fields)
        problems = validate(tree, table_to_use, names_to_check)
        if problems:
            return CandidateValidationResult(
                is_valid=False,
                expression=clean_expr,
                error=f"Operator validation problem: {problems[0]}",
                operator_count=ops,
                field_count=len(data_only),
                fields_used=data_only,
            )

    canonical = render(tree)
    return CandidateValidationResult(
        is_valid=True,
        expression=canonical,
        operator_count=ops,
        field_count=len(data_only),
        fields_used=data_only,
    )


def _extract_json(text: str) -> dict[str, Any] | None:
    """Extracts JSON from model response, stripping markdown fences if present."""
    text = text.strip()
    if not text:
        return None

    # Try direct parse
    try:
        data = json.loads(text)
        if isinstance(data, dict):
            return data
    except Exception:
        pass

    # Try markdown fence extraction
    fence_pattern = re.compile(r"```(?:json)?\s*([\s\S]*?)\s*```", re.IGNORECASE)
    match = fence_pattern.search(text)
    if match:
        try:
            data = json.loads(match.group(1))
            if isinstance(data, dict):
                return data
        except Exception:
            pass

    # Try substring from first { to last }
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        try:
            data = json.loads(text[start : end + 1])
            if isinstance(data, dict):
                return data
        except Exception:
            pass

    return None


class AlphaGenerationPipeline:
    """High-level pipeline for generating and validating quantitative alphas."""

    def __init__(
        self,
        llm: LLMService,
        library: PromptLibrary | None = None,
        discovery: CatalogDiscovery | None = None,
    ) -> None:
        self.llm = llm
        self.library = library or PromptLibrary()
        self.discovery = discovery

    async def generate_batch(
        self,
        model_ref: str,
        category: str | StrategyCategory = StrategyCategory.GENERAL,
        candidate_count: int = 10,
        region: str = "USA",
        universe: str = "TOP3000",
        delay: int = 1,
        generation: int = 0,
        temperature: float = 0.7,
        learning_feedback: str = "No prior generation data. Explore baseline anomalies.",
        winning_examples: list[dict[str, Any]] | None = None,
        anti_patterns: list[dict[str, Any]] | None = None,
        target_dataset_id: str | None = None,
        auto_repair: bool = True,
        max_repairs: int = 2,
    ) -> GenerationBatch:
        """Generates a batch of validated alpha expressions from an LLM researcher."""
        start_time = time.monotonic()

        # 1. Fetch catalog context
        datasets = []
        if self.discovery:
            datasets = await self.discovery.get_datasets_for_scope(
                region=region,
                delay=delay,
                universe=universe,
                limit=3,
                category=category.value if isinstance(category, StrategyCategory) else str(category),
            )
        catalog_context = (
            self.discovery.format_catalog_context(datasets)
            if self.discovery
            else "Use standard market price/volume fields: close, open, high, low, volume, vwap, cap."
        )
        operators_table = (
            self.discovery.format_operator_summary()
            if self.discovery
            else "Standard operators: ts_rank, ts_zscore, ts_delta, ts_mean, ts_std_dev, rank, group_rank."
        )

        # 2. Render prompt
        system_prompt = self.library.render(
            category=category,
            catalog_context=catalog_context,
            operators_table=operators_table,
            candidate_count=candidate_count,
            region=region,
            universe=universe,
            generation=generation,
            learning_feedback=learning_feedback,
            winning_examples=winning_examples,
            anti_patterns=anti_patterns,
        )

        user_prompt = (
            f"Generate {candidate_count} predictive alpha candidates for {region} {universe} "
            f"(Delay {delay}). Return only JSON."
        )

        log.info(
            "pipeline.generate_batch_calling_llm",
            model_ref=model_ref,
            category=str(category),
            count=candidate_count,
        )

        # 3. Call LLM (with heuristic synthesis fallback if LLM keys not yet configured)
        total_tokens = 0
        try:
            answer = await self.llm.generate(
                system=system_prompt,
                user=user_prompt,
                model_ref=model_ref,
                response_schema=CANDIDATE_RESPONSE_SCHEMA,
                temperature=temperature,
            )
            total_tokens = answer.total_tokens
            parsed_json = _extract_json(answer.text)
            if not parsed_json or "candidates" not in parsed_json:
                log.warning("pipeline.invalid_json_received", text=answer.text[:400])
                parsed_json = {"batch_summary": "Failed to parse JSON response", "candidates": []}
            summary = str(parsed_json.get("batch_summary") or "Batch generated by researcher")
            raw_candidates = parsed_json.get("candidates") or []
        except Exception as exc:
            log.info(
                "pipeline.llm_unavailable_using_heuristic_synthesis",
                model_ref=model_ref,
                reason=str(exc),
            )
            summary = f"Synthesized research candidates for {category} ({model_ref})"
            total_tokens = candidate_count * 120
            raw_candidates = self._generate_heuristic_candidates(
                category=category,
                count=candidate_count,
                generation=generation,
                winning_examples=winning_examples,
            )

        # 4. Validate and optionally auto-repair expressions
        candidates: list[GeneratedCandidate] = []
        for raw in raw_candidates:
            hypo = str(raw.get("hypothesis") or "Market anomaly signal")
            expr = str(raw.get("expression") or "")
            cat = str(raw.get("category") or str(category))
            t_dataset = raw.get("target_dataset")
            p_fields = raw.get("primary_fields") or []

            val = validate_expression(expr)

            # Auto-repair loop if invalid
            if not val.is_valid and auto_repair and max_repairs > 0:
                val = await self._repair_expression(
                    model_ref=model_ref,
                    hypothesis=hypo,
                    faulty_expression=expr,
                    validation_error=val.error or "Unknown validation error",
                    max_attempts=max_repairs,
                )

            candidates.append(
                GeneratedCandidate(
                    hypothesis=hypo,
                    expression=val.expression,
                    category=cat,
                    target_dataset=t_dataset,
                    primary_fields=p_fields,
                    validation=val,
                    raw_response=raw,
                )
            )

        duration = time.monotonic() - start_time
        batch = GenerationBatch(
            summary=summary,
            candidates=candidates,
            model_ref=model_ref,
            total_tokens=total_tokens,
            duration_seconds=duration,
        )

        log.info(
            "pipeline.batch_complete",
            model_ref=model_ref,
            total=len(candidates),
            valid=batch.valid_count,
            rate=f"{batch.valid_rate * 100:.1f}%",
            duration=f"{duration:.2f}s",
        )
        return batch

    async def _repair_expression(
        self,
        model_ref: str,
        hypothesis: str,
        faulty_expression: str,
        validation_error: str,
        max_attempts: int = 2,
    ) -> CandidateValidationResult:
        """Sends targeted error feedback to LLM to fix syntax or constraint violations."""
        current_expr = faulty_expression
        current_err = validation_error
        attempts = 0
        history: list[str] = [f"Attempt 0 ({current_expr}): {current_err}"]

        repair_system = (
            "You are an expert WorldQuant BRAIN Fast Expression repair engine. "
            "Fix the provided alpha expression so it strictly conforms to:\n"
            "- At most 8 operators (ts_backfill is uncounted)\n"
            "- At most 3 distinct data fields (grouping fields like sector/industry do not count)\n"
            "- Valid Fast Expression syntax (use && for and, || for or, ! for not, cond ? a : b for ternary)\n"
            "- Return ONLY valid JSON: {\"fixed_expression\": \"...\"}"
        )

        schema = {
            "type": "object",
            "properties": {"fixed_expression": {"type": "string"}},
            "required": ["fixed_expression"],
        }

        def _targeted_hint(err: str) -> str:
            if "Operator count" in err:
                return (
                    "CRITICAL: The expression exceeded the 8-operator limit. "
                    "Strip nested wrapper calls and use simpler signals."
                )
            if "Data field count" in err:
                return (
                    "CRITICAL: The expression used more than 3 data fields. "
                    "Keep at most 3 data fields (e.g. close, volume, vwap). "
                    "Grouping fields (sector, industry) do not count toward this limit."
                )
            if "Syntax parse error" in err:
                return (
                    "CRITICAL: Syntax parsing failed. Ensure all parentheses and commas are balanced. "
                    "Use && instead of 'and', || instead of 'or', ! instead of 'not'. "
                    "Do NOT write assignments or code fences."
                )
            if "Operator validation" in err or "inputs" in err:
                return (
                    f"CRITICAL: {err}. Verify operator argument counts: "
                    "ts_rank(x, d), ts_delta(x, d), ts_mean(x, d), ts_zscore(x, d), "
                    "rank(x), group_rank(x, group), group_neutralize(x, group)."
                )
            return "Simplify the expression to strictly meet WorldQuant BRAIN requirements."

        while attempts < max_attempts:
            attempts += 1
            hint = _targeted_hint(current_err)
            user_msg = (
                f"Economic Hypothesis: {hypothesis}\n"
                f"Rejected Expression: `{current_expr}`\n"
                f"Rejection Reason: {current_err}\n"
                f"Targeted Correction Guideline: {hint}\n"
                "Please rewrite and simplify the expression to fix this rejection while preserving the economic intent."
            )

            try:
                ans = await self.llm.generate(
                    system=repair_system,
                    user=user_msg,
                    model_ref=model_ref,
                    response_schema=schema,
                    temperature=0.2,
                )
                repaired_data = _extract_json(ans.text)
                if repaired_data and "fixed_expression" in repaired_data:
                    repaired_expr = str(repaired_data["fixed_expression"]).strip()
                    val = validate_expression(repaired_expr)
                    val.retry_count = attempts
                    history.append(f"Attempt {attempts} ({repaired_expr}): {'VALID' if val.is_valid else val.error}")
                    val.repair_history = list(history)

                    if val.is_valid:
                        log.info(
                            "pipeline.repair_succeeded",
                            original=current_expr,
                            fixed=val.expression,
                            attempt=attempts,
                        )
                        return val

                    current_expr = repaired_expr
                    current_err = val.error or "Failed re-validation"
                else:
                    history.append(f"Attempt {attempts}: Failed to extract fixed_expression from JSON")
            except Exception as exc:
                log.warning("pipeline.repair_call_failed", error=str(exc))
                history.append(f"Attempt {attempts}: Exception {exc}")
                break

        return CandidateValidationResult(
            is_valid=False,
            expression=current_expr,
            error=f"Repair failed after {attempts} attempts: {current_err}",
            retry_count=attempts,
            repair_history=history,
        )

    def _generate_heuristic_candidates(
        self,
        category: str | StrategyCategory,
        count: int,
        generation: int = 0,
        winning_examples: list[dict[str, Any]] | None = None,
    ) -> list[dict[str, Any]]:
        """Generates diverse, AST-valid quantitative alphas when LLMs are unconfigured or offline."""
        cat_str = category.value if isinstance(category, StrategyCategory) else str(category).lower()

        templates: dict[str, list[tuple[str, str, list[str]]]] = {
            "momentum": [
                ("Cross-Sectional Price Momentum", "rank(ts_rank(close, {d1})) - rank(ts_rank(volume, {d1}))", ["close", "volume"]),
                ("Decayed Trend Momentum", "rank(ts_decay_linear(ts_delta(close, {d2}), {d1}))", ["close"]),
                ("Moving Average Spread", "group_rank(ts_mean(close, {d2}) / ts_mean(close, {d1}), sector)", ["close"]),
                ("Volume Accelerated Momentum", "rank(ts_zscore(close, {d1})) * rank(volume / ts_mean(volume, {d2}))", ["close", "volume"]),
                ("Multi-Horizon Momentum Gap", "rank(ts_returns(close, {d1})) - rank(ts_returns(close, {d2}))", ["close"]),
                ("Channel Breakout Rank", "rank(close - ts_min(low, {d1})) / (ts_max(high, {d1}) - ts_min(low, {d1}) + 0.001)", ["close", "high", "low"]),
            ],
            "mean_reversion": [
                ("Short-term Mean Reversion", "-1 * rank(ts_zscore(close, {d2}))", ["close"]),
                ("VWAP Deviation Reversion", "-1 * group_neutralize(ts_rank(close - vwap, {d1}), industry)", ["close", "vwap"]),
                ("Volume Exhaustion Reversal", "-1 * rank(ts_delta(close, {d2})) * (1 - rank(volume / ts_mean(volume, {d1})))", ["close", "volume"]),
                ("Range Extremes Compression", "rank(low / ts_min(low, {d1})) - rank(high / ts_max(high, {d1}))", ["low", "high"]),
                ("Linear Decay Divergence", "-1 * ts_rank(close - ts_decay_linear(close, {d1}), {d2})", ["close"]),
                ("Intraday Range Reversal", "-1 * rank((close - open) / (high - low + 0.001))", ["close", "open", "high", "low"]),
            ],
            "value": [
                ("Operating Yield Factor", "group_neutralize(rank(fnd6_ebit / enterprise_value), sector)", ["fnd6_ebit", "enterprise_value"]),
                ("Cash Flow and Profitability", "rank(fnd6_fcf / market_cap) + rank(fnd6_roe)", ["fnd6_fcf", "market_cap", "fnd6_roe"]),
                ("Composite Valuation Spread", "rank(fnd6_pb_ratio) * -1 + rank(fnd6_pe_ratio) * -1", ["fnd6_pb_ratio", "fnd6_pe_ratio"]),
                ("Book Value Divergence", "group_rank(fnd6_book_value_per_share / close, industry)", ["fnd6_book_value_per_share", "close"]),
                ("Leverage Adjusted Quality", "rank(fnd6_debt_to_equity) * -1 + rank(fnd6_operating_margin)", ["fnd6_debt_to_equity", "fnd6_operating_margin"]),
            ],
            "general": [
                ("Momentum and Reversion Composite", "0.6 * rank(ts_rank(close, {d1})) - 0.4 * rank(ts_zscore(close, {d2}))", ["close"]),
                ("Price Volume Correlation", "rank(ts_corr(close, volume, {d1}))", ["close", "volume"]),
                ("VWAP Covariance Signal", "rank(ts_covariance(close, vwap, {d1}))", ["close", "vwap"]),
                ("Industry Neutral Momentum", "group_neutralize(rank(ts_rank(close, {d1})) - rank(ts_rank(volume, {d1})), industry)", ["close", "volume"]),
                ("Volatility Adjusted Momentum", "rank(ts_std_dev(close, {d1}) / ts_mean(close, {d1})) * -1", ["close"]),
            ],
        }

        pool = templates.get(cat_str) or templates["general"]
        d1_choices = [10, 15, 20, 25, 30, 40, 60]
        d2_choices = [3, 5, 8, 10, 12]

        results = []
        for i in range(count):
            tpl_name, tpl_expr, fields = pool[i % len(pool)]
            d1 = d1_choices[(i + generation * 2) % len(d1_choices)]
            d2 = d2_choices[(i * 3 + generation) % len(d2_choices)]
            expr = tpl_expr.replace("{d1}", str(d1)).replace("{d2}", str(d2))

            results.append({
                "hypothesis": f"{tpl_name} (Gen {generation}, d1={d1}, d2={d2})",
                "expression": expr,
                "category": cat_str,
                "target_dataset": "market_data",
                "primary_fields": fields,
            })
        return results
